version: 2.1

jobs:
  build:
    docker:
      - image: node:lts
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: schemats
    working_directory: ~/schemats
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn run tsc
      - run: yarn run example:postgres
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - example

  release:
    docker: 
      - image: node:lts
    working_directory: ~/schemats
    steps:
      - attach_workspace:
          at: ~/schemats
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  
  develop:
    jobs:
      - build:
          filters:
               tags:
                  ignore: /^v.*/

  release:
      jobs:
        - build:
            filters:
                tags:
                  only: /^v.*/
                branches:
                  ignore: /.*/
        - release:
            requires:
              - build
            